@startuml SD_hypCut
title: Gombafonal vágása

actor Rovarász
participant ":Game" as Game
participant "Entomologist:Player" as Player
participant ":Insect" as Insect
participant ":Hypha" as Hypha
'participant ":Tecton" as Tecton

Rovarász -> Game: SelectAction()
activate Game

Game -> Player: SelectAction()

deactivate Game 
activate Player

Player -> Insect: cutHypha(Hypha, Tecton)
deactivate Player

activate Insect
activate Hypha
Insect -> Hypha: getTectons()
Hypha --> Insect: List<Tecton>
deactivate Hypha

deactivate Insect


    alt lifespam == 0
    activate Game
    Hypha -> Game: decayedHypha.add(this)
    deactivate Game
    end

deactivate Player
deactivate Game
@enduml