@startuml SD_hypCut

actor Rovarász
participant ":Game" as Game
participant "Entomologist:Player" as Player
participant ":Insect" as Insect
participant ":Hypha" as Hypha
participant ":Tecton" as Tecton

Rovarász -> Game: SelectAction()
activate Game

Game -> Player: SelectAction()
activate Player

Player -> Insect: cutHypha(Hypha, Tecton)
activate Insect

Insect -> Hypha: getTectons()
Hypha --> Insect: List<Tecton>

Insect -> Hypha: continueHypha(Tecton)
activate Hypha

alt nem KeepHyphaTecton
    Hypha -> Game: decayedHypha.add(this)
end

Hypha --> Insect: true
deactivate Hypha

Insect --> Player: true
deactivate Insect

Player --> Game: action done
deactivate Player
deactivate Game
@enduml