@startuml

== 5. Spóra hatás alkalmazása ==
actor Insect
participant Spore

Insect -> Spore: applyEffect()
activate Spore

alt AcceleratingEffect
    Spore -> Insect: increaseMovement()
    Insect --> Spore: movement buff applied
else SlowingEffect
    Spore -> Insect: decreaseMovement()
    Insect --> Spore: movement debuff applied
else ParalyzingEffect
    Spore -> Insect: disableMovement()
    Insect --> Spore: movement disabled
else StunningEffect
    Spore -> Insect: disableHyphaCutting()
    Insect --> Spore: hypha cutting disabled
else NoEffect
    Spore --> Insect: No changes
end

Spore -> Insect: applyNutrientValue()
Spore --> Insect: modify attributes

deactivate Spore

@enduml
