@startuml SD_tctType

title Tecton Típusok

actor "Játék Logika" as JatekLogika
participant ":Game" as Game
participant ":GameBoard" as GameBoard
participant ":NoFungiTecton" as NoFungiTecton
participant ":ShortHyphaTecton" as ShortHyphaTecton
participant ":InfiniteHyphaTecton" as InfiniteHyphaTecton
participant ":SingleHyphaTecton" as SingleHyphaTecton
participant ":KeepHyphaTecton" as KeepHyphaTecton

JatekLogika -> Game: initGame()
activate Game

Game -> GameBoard: generateBoard()
activate GameBoard

GameBoard -> NoFungiTecton: new NoFungiTecton()
activate NoFungiTecton
note right of NoFungiTecton: [fungiEnabled=false]
NoFungiTecton --> GameBoard: return tecton
deactivate NoFungiTecton

GameBoard -> ShortHyphaTecton: new ShortHyphaTecton()
activate ShortHyphaTecton
note right of ShortHyphaTecton: [hyphaLifespan=4]
ShortHyphaTecton --> GameBoard: return tecton
deactivate ShortHyphaTecton

GameBoard -> InfiniteHyphaTecton: new InfiniteHyphaTecton()
activate InfiniteHyphaTecton
note right of InfiniteHyphaTecton: [hyphaLimit=-1]
InfiniteHyphaTecton --> GameBoard: return tecton
deactivate InfiniteHyphaTecton

GameBoard -> SingleHyphaTecton: new SingleHyphaTecton()
activate SingleHyphaTecton
note right of SingleHyphaTecton: [hyphaLimit=1]
SingleHyphaTecton --> GameBoard: return tecton
deactivate SingleHyphaTecton

GameBoard -> KeepHyphaTecton: new KeepHyphaTecton()
activate KeepHyphaTecton
note right of KeepHyphaTecton: [lifespam=-1]
KeepHyphaTecton --> GameBoard: return tecton
deactivate KeepHyphaTecton

GameBoard --> Game: return List <Tecton>
deactivate GameBoard

Game --> JatekLogika: board ready
deactivate Game
@enduml