@startuml

== 1. Rovar lépés ==
actor Entomologist
participant Insect
participant GameBoard
participant Tecton

Entomologist -> Insect: move(Tecton target)
activate Insect

Insect -> GameBoard: getNeighbors(Tecton current)
activate GameBoard
GameBoard --> Insect: return List<Tecton>
deactivate GameBoard

Insect -> Tecton: getHypha()
activate Tecton
Tecton --> Insect: return Hypha (if exists)
deactivate Tecton

alt Van fonál
    Insect -> Tecton: move(target)
    activate Tecton
    Tecton --> Insect: return boolean 
    deactivate Tecton
else Nincs fonál
    Insect --> Entomologist: Nincs mozgás 
end

deactivate Insect

@enduml
