@startuml

== 10. Játékos kör kezelése ==
actor Game
participant Player
participant GameBoard
participant Tecton
participant Spore

Game -> Player: startGame()
activate Player

loop Akciók végrehajtása
    Player -> Player: selectAction()
    alt Gombász (Mycologist)
        Player -> Player: spreadSpores()
        Player -> Player: growHypha()
    else Rovarász (Entomologist)
        Player -> Player: move()
        Player -> Player: cutHypha()
        Player -> Player: consumeSpores()
    end
end

deactivate Player

Game -> GameBoard: handleTurn()
activate GameBoard
loop Minden tectonon
    GameBoard -> Tecton: update()
    alt ShortHyphaTecton
        Tecton -> Tecton: hyphaLifespan--;
    end
end
deactivate GameBoard

Game -> Spore: update()
deactivate Spore

Game -> Game: nextTurn()

@enduml