@startuml

== 2. Játék Sikertelen Inicializálása V1==

actor Player
participant Game

Player -> Game: InitGame(int PlayerCount, int MycologistCount, int EntomologistCount, int RoundCount)
activate Game
Game --> Player: return false

@enduml