# before merging a PR the code MUST compile and pass the tests
name: Verify Maven Build

on:
  pull_request:
    branches:
      - master  # vagy main, attól függ, nálatok mi az alap

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '20'  # vagy amit a projekt használ

      - name: Compile project
        run: mvn compile
