# Java CI with Maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.13.0
        with:
          maven-version: '3.9.6'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload dependency graph
        uses: advanced-security/maven-dependency-submission-action@v1
