# before merging a PR the code MUST compile and pass the tests
name: Verify Maven Build

on:
  pull_request:
    branches:
      - master  # vagy main, attól függ, nálatok mi az alap

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Display Java version (debug)
        run: java -version

      - name: Display Maven version (debug)
        run: mvn --version

      - name: Set JAVA_HOME for Maven
        run: echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV

      - name: Compile project
        run: mvn compile
