name: Verify Maven Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Install Maven 3.9.6
        uses: s4u/setup-maven-action@v1
        with:
          maven-version: 3.9.6

      - name: Display Java version (debug)
        run: java -version

      - name: Display Maven version (debug)
        run: mvn --version

      - name: Compile project
        run: mvn compile
